### ISSUE TITLE
log_catalog is off, but still some catalog SQL is logged

### ISSUE THREAD

**Issue by majgab8852** [pgaudit/pgaudit#217]
I have installed pgaudit on top of Postgres 15 with Patroni, using the Percona repo. I disabled the log_catalog setting in the Patroni yaml:

```
postgresql:
  listen: ...
  parameters:
    ...
    log_destination: 'stderr,csvlog'
    log_filename: 'postgresql-%Y%m%d.log'
    log_line_prefix: '%m - Process=[%p], Application=[%a], User=[%u]@[%r]/[%d], SessionID=[%c], Session start=[%s]: '
    log_min_duration_statement: 1000ms
    log_min_duration_sample: 250ms
    log_statement_sample_rate: 0.5
    log_statement: 'ddl'
    log_checkpoints: on
    log_connections: on
    log_disconnections: on
    log_duration: on
    log_lock_waits: on
    ...
    pgaudit.log: all
    pgaudit.log_catalog: off
    pgaudit.log_parameter: on
    pgaudit.log_directory: 'log'
    pgaudit.log_filename: 'audit-%Y%m%d.csv'
    pgaudit.log_rotation_age: 1d
    pgaudit.log_connections: on
    pgaudit.log_disconnections: on
```

I tried ```pgaudit.log_catalog: off``` and ```pgaudit.log_catalog: 'off'``` ('off' in apostrophes), same result. Both should be correct, based on the generated settings in the database itself:

```
postgres=# select name, setting, source from pg_settings where name like '%audit%';
            name            |     setting      |       source
----------------------------+------------------+--------------------
 pgaudit.log                | all              | configuration file
 pgaudit.log_catalog        | off              | configuration file
 pgaudit.log_client         | off              | default
 pgaudit.log_connections    | on               | configuration file
 pgaudit.log_directory      | log              | configuration file
 pgaudit.log_disconnections | on               | configuration file
 pgaudit.log_filename       | audit-%Y%m%d.csv | configuration file
 pgaudit.log_level          | log              | default
 pgaudit.log_parameter      | on               | configuration file
 pgaudit.log_relation       | off              | default
 pgaudit.log_rotation_age   | 1440             | configuration file
 pgaudit.log_rows           | off              | default
 pgaudit.log_statement      | on               | default
 pgaudit.log_statement_once | off              | default
 pgaudit.role               |                  | default
(15 rows)
```

Still I get messages in the audit log like so:

```
2023-06-12 09:17:52.084 CEST,postgres,postgres,1043011,127.0.0.1:53738,6486c664.fea43,9,SELECT,2023-06-12 09:16:52 CEST,3/91,0,00000,SESSION,7,1,READ,SELECT,,,"SELECT CASE WHEN pg_catalog.pg_is_in_recovery() THEN 0 ELSE ('x' || pg_catalog.substr(pg_catalog.pg_walfile_name(pg_catalog.pg_current_wal_lsn()), 1, 8))::bit(32)::int END, CASE WHEN pg_catalog.pg_is_in_recovery() THEN 0 ELSE pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_current_wal_lsn(), '0/0')::bigint END, pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_last_wal_replay_lsn(), '0/0')::bigint, pg_catalog.pg_wal_lsn_diff(COALESCE(pg_catalog.pg_last_wal_receive_lsn(), '0/0'), '0/0')::bigint, pg_catalog.pg_is_in_recovery() AND pg_catalog.pg_is_wal_replay_paused(), 0, CASE WHEN latest_end_lsn IS NULL THEN NULL ELSE received_tli END, slot_name, conninfo, NULL, 'on', '', NULL FROM pg_catalog.pg_stat_get_wal_receiver()",<none>,,,,,,,,,Patroni
```

Formatted SQL for better readability:

```SQL
SELECT
  CASE
    WHEN pg_catalog.pg_is_in_recovery() THEN 0
    ELSE ('x' || pg_catalog.substr(pg_catalog.pg_walfile_name(pg_catalog.pg_current_wal_lsn()), 1, 8))::bit(32)::int
  END,
  CASE
    WHEN pg_catalog.pg_is_in_recovery() THEN 0
    ELSE pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_current_wal_lsn(), '0/0')::bigint
  END,
  pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_last_wal_replay_lsn(), '0/0')::bigint,
  pg_catalog.pg_wal_lsn_diff(COALESCE(pg_catalog.pg_last_wal_receive_lsn(), '0/0'), '0/0')::bigint,
  pg_catalog.pg_is_in_recovery() AND pg_catalog.pg_is_wal_replay_paused(),
  0,
  CASE
    WHEN latest_end_lsn IS NULL THEN NULL
    ELSE received_tli
  END,
  slot_name,
  conninfo,
  NULL,
  'on',
  '',
  NULL
FROM
  pg_catalog.pg_stat_get_wal_receiver()
```

I think this satisfies the definition for pgaudit.log_catalog, that is "all relations in a statement are in pg_catalog". I guess somehow this statement slips through? Or I'm completely blind and not seeing which relation is outside of the pg_catalog.
